FROM brandonmosher/devcontainer-azureagent

ENV BASH_ENV=/etc/profile
ENV NODE_VERSION=15

ARG NODE_GYP_DEPENDENCIES="python2 build-essential"

COPY dotnet/utils/ node/utils/ .
COPY node/utils/nvm-activate.sh /etc/profile.d

RUN sudo ./dotnet-install.sh && \
    ./npm-install.sh --node-version ${NODE_VERSION} && \
    sudo apt-helper --no-upgrade git ${NODE_GYP_DEPENDENCIES}